services:
  - type: web
    name: api-resumo-pdf
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: OPENAI_API_KEY
        sync: false 